### ISSUE TITLE
updating file in an existing record

### ISSUE THREAD

**Issue by kristiholmes** [galterlibrary/InvenioRDM-at-NU#473]
Something to look into down to road:
I want to upload an updated version of the deposited file. I cannot delete the first file and the upload of the updated file fails before completion. 

(In the interest of time, I made a new record, please delete this record: https://vtfsmghslapps04.fsm.northwestern.edu/records/e84a3bd6df2b476e8f59b3c9fb387877)

**Comment by fenekku** [comment]
Yes. The current functionality is intentional because versioning is hidden. We don't allow creation of explicit new version which would be the only way to update a file. This will be available in the final version. File upload is being worked on currently in the invenio-sprint by people at CERN. 

Closing this in favour of re-worded #401
